spring:
  application:
    name: Auth-Service
  datasource:
    url: jdbc:mysql://localhost:3306/userecommersedb
    username: root
    password: Baku2018
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8083
jwt:
  secret: a-string-secret-at-least-256-bits-long
  expiration: 3600000