version: '3.8'
services:
  auth-service:
    build:
      context: ./Auth-Service
    ports:
      - "8081:8081"
    networks:
      - microservice-network

  product-service:
    build:
      context: ./product-service
    ports:
      - "8082:8082"
    depends_on:
      - auth-service
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge