spring:
  application:
    name: PRODUCT-SERVICE
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/productecommersedb
    username: root
    password: Baku2018
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.139
    instance-id: ${spring.application.name}:${random.value}
    hostname: 192.168.1.139
    non-secure-port: 8087

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000