spring:
  application:
    name: Product-Service
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/productecommersedb
    username: root
    password: Baku2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8084
eureka:
  client:
  service-url:
    defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000